### ISSUE TITLE
run these programs

### ISSUE THREAD

**Issue by MingfangDeng** [FlyEgle/MAE-pytorch#1]
how to run these programs?can you tell me details? the readme is not clearly.thank you very much.

**Comment by FlyEgle** [comment]
1. You need prepare the imagenet train log like my readme format.
2. And you can run my training bash code to train the pretrain model.
3. If you only have one gpu, you need modify the 
`CUDA_VISIBLE_DEVICES=0 python -W ignore -m torch.distributed.launch --nproc_per_node 1 train_mae.py` 
4. My FineTune and Linear-prob may train as soon as possible.
5. I think my readme is easy for read, if you have possible may read paper first, thx.
