### ISSUE TITLE
load_state_dict, size mismatch

### ISSUE THREAD

**Issue by ichiyasa0308** [FlyEgle/MAE-pytorch#7]
Hi
I’m not good at pytorch modeling, but how can I download the pretrained weight for inference.py?

I downloaded  pretrained weight as you mentioned below, but I can’t load correctly.
>Vit-Tiny/16 pretrain models is here
>Vit-Base/16 pretrain models is here

error message is 

> load_state_dict, size mismatch for cls_token:copying a param with shape torch.Size([1,1,192)] from check point, the shape in current model is torch.Size([1,1,768]).

It seems that /model/Transformers/VIT/mae.py  line around 200 is incorrect.
 thank you for reading.

**Comment by FlyEgle** [comment]
Because the weights is vit-tiny，and you want load this weights to vit-base.
You can see the readme model config, follow this to modify the vit model dims.
![1640853624(1)](https://user-images.githubusercontent.com/26165705/147735582-e2c9f561-8120-48e4-ab35-374fb3b93c14.png)
